@url = http://localhost:3000
### 
GET {{url}}/hello HTTP/1.1
 
### 请求字符串
GET {{url}}/querystring?name=franck-lynn&password=123456

### 请求参数
GET {{url}}/queryparams/commentId HTTP/1.1 

### 请求参数后面 + 请求字符串
GET {{url}}/queryparams/commentId?name=franck-lynn&password=123456 HTTP/1.1 

### 测试 req.body
POST {{url}}/reqbody HTTP/1.1
Content-Type: application/json

{
  "name": "franck",
  "password": "123"
}


### 测试文件上传
POST {{url}}/uploads HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundarymZBeJBrIvRUzdN3r

------WebKitFormBoundarymZBeJBrIvRUzdN3r
Content-Disposition: form-data; name="file"; filename="20230313170434.jpg"
Content-Type: image/jpeg

< ./05.测试要上传的图片.jpg
------WebKitFormBoundarymZBeJBrIvRUzdN3r--