export enum HttpStatus {
  CONTINUE = 100, //("Continue"),  // 继续
  SWITCHING_PROTOCOLS = 101, //("Switching Protocols") , // 切换协议
  PROCESSING = 102, //("Processing") , // 执行
  CHECKPOINT = 103, //("Checkpoint") , // 检查点
  OK = 200, //("OK") , // OK
  CREATED = 201, //("Created"), // 创建
  ACCEPTED = 202, //("Accepted"),// 接受
  NON_AUTHORITATIVE_INFORMATION = 203, //("Non-Authoritative Information"), // 非权威信息
  NO_CONTENT = 204, //("No Content"),//没有内容
  RESET_CONTENT = 205, //("Reset Content"),//重置内容
  PARTIAL_CONTENT = 206, //("Partial Content"),//部分内容
  MULTI_STATUS = 207, //("Multi-Status"),//多个状态
  ALREADY_REPORTED = 208, //("Already Reported"),//已发
  IM_USED = 226, //("IM Used"),//已过时
  MULTIPLE_CHOICES = 300, //("Multiple Choices"),//多选择
  MOVED_PERMANENTLY = 301, //("Moved Permanently"),//永久移动
  FOUND = 302, //("Found"),//找到
  SEE_OTHER = 303, //("See Other"),//参见其它
  NOT_MODIFIED = 304, //("Not Modified"),//未修改
  TEMPORARY_REDIRECT = 307, //("Temporary Redirect"),//暂时重定向
  PERMANENT_REDIRECT = 308, //("Permanent Redirect"),//永久重定向
  BAD_REQUEST = 400, //("Bad Request"),//错误请求
  UNAUTHORIZED = 401, //("Unauthorized"),//未经授权
  PAYMENT_REQUIRED = 402, //("Payment Required"),//付费请求
  FORBIDDEN = 403, //("Forbidden"),//禁止
  NOT_FOUND = 404, //("Not Found"),//未找到
  METHOD_NOT_ALLOWED = 405, //("Method Not Allowed"),//方法不容许
  NOT_ACCEPTABLE = 406, //("Not Acceptable"),//方法不接受
  PROXY_AUTHENTICATION_REQUIRED = 407, //("Proxy Authentication Required"),//需要代理身份验证
  REQUEST_TIMEOUT = 408, //("Request Timeout"),//请求超时
  CONFLICT = 409, //("Conflict"),//指令冲突
  GONE = 410, //("Gone"),//文档不在当前地址
  LENGTH_REQUIRED = 411, //("Length Required"),//需要Content-Length头请求
  PRECONDITION_FAILED = 412, //("Precondition Failed"),//前提条件失败
  PAYLOAD_TOO_LARGE = 413, //("Payload Too Large"),//请求实体太大
  URI_TOO_LONG = 414, //("URI Too Long"),//请求URI太长
  UNSUPPORTED_MEDIA_TYPE = 415, //("Unsupported Media Type"),//不支持的媒体类型
  REQUESTED_RANGE_NOT_SATISFIABLE = 416, //("Requested range not satisfiable"),//请求的范围不可满足
  EXPECTATION_FAILED = 417, //("Expectation Failed"),//期望失败
  I_AM_A_TEAPOT = 418, //("I'm a teapot"),//服务器拒绝冲泡咖啡
  UNPROCESSABLE_ENTITY = 422, //("Unprocessable Entity"),//语义错误，无法响应请求
  LOCKED = 423, //("Locked"),//请求资源被锁定
  FAILED_DEPENDENCY = 424, //("Failed Dependency"),//由于之前的某个请求发生的错误，导致当前请求失败
  TOO_EARLY = 425, //("Too Early"),//太早
  UPGRADE_REQUIRED = 426, //("Upgrade Required"),//客户端应当切换到TLS/1.0
  PRECONDITION_REQUIRED = 428, //("Precondition Required"),//需要先决条件
  TOO_MANY_REQUESTS = 429, //("Too Many Requests"),//太多请求
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431, //("Request Header Fields Too Large"),//请求头太大
  UNAVAILABLE_FOR_LEGAL_REASONS = 451, //("Unavailable For Legal Reasons"),//法律原因不可用
  INTERNAL_SERVER_ERROR = 500, //("Internal Server Error"),//服务器遇到了意料不到的情况，不能完成客户的请求
  NOT_IMPLEMENTED = 501, //("Not Implemented"),//服务器不支持实现请求所需要的功能
  BAD_GATEWAY = 502, //("Bad Gateway"),//从上游服务器接收到无效的响应
  SERVICE_UNAVAILABLE = 503, //("Service Unavailable"),//服务不可用
  GATEWAY_TIMEOUT = 504, //("Gateway Timeout"),//网关不能及时地从远程服务器获得应答
  HTTP_VERSION_NOT_SUPPORTED = 505, //("HTTP Version not supported"),//服务器不支持请求中使用的HTTP版本
  VARIANT_ALSO_NEGOTIATES = 506, //("Variant Also Negotiates"),//内容协商的循环引用
  INSUFFICIENT_STORAGE = 507, //("Insufficient Storage"),//服务器无法存储完成请求所必须的内容
  LOOP_DETECTED = 508, //("Loop Detected"),//服务器处理请求时检测到一个无限循环
  BANDWIDTH_LIMIT_EXCEEDED = 509, //("Bandwidth Limit Exceeded"),//超过带宽的限制 服务器暂时无法提供服务
  NOT_EXTENDED = 510, //("Not Extended"),//请求需要延期
  NETWORK_AUTHENTICATION_REQUIRED = 511, //("Network Authentication Required");//客户端需要进行身份验证以获得网络访问
}
