import { Decimal } from "decimal.js"
import { TableBodyType } from "./types"

export const tableBody: TableBodyType[] = [
  {
    item_no: 1,
    name: "美夹新倍比高精度弹簧夹头",
    catalog_number: "BBT30-MEGA6N-60",
    qty: 1,
    price: new Decimal(1504.97),
    amount: new Decimal(1504.97),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 2,
    name: "美夹新倍比高精度弹簧夹头",
    catalog_number: "BBT30-MEGA6N-90",
    qty: 1,
    price: new Decimal(1536.15),
    amount: new Decimal(1536.15),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 3,
    name: "美夹新倍比高精度弹簧夹头",
    catalog_number: "BBT30-MEGA10N-90",
    qty: 1,
    price: new Decimal(1504.97),
    amount: new Decimal(1504.97),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 4,
    name: "美夹新倍比高精度弹簧夹头",
    catalog_number: "BBT30-MEGA16N-90",
    qty: 1,
    price: new Decimal(1593.3),
    amount: new Decimal(1593.3),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 5,
    name: "新倍比夹套",
    catalog_number: "NBC6-4",
    qty: 1,
    price: new Decimal(277.09),
    amount: new Decimal(277.09),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 6,
    name: "新倍比夹套",
    catalog_number: "NBC6-6",
    qty: 1,
    price: new Decimal(277.09),
    amount: new Decimal(277.09),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 7,
    name: "新倍比夹套",
    catalog_number: "NBC10-4",
    qty: 1,
    price: new Decimal(281.42),
    amount: new Decimal(281.42),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 8,
    name: "新倍比夹套",
    catalog_number: "NBC10-6",
    qty: 1,
    price: new Decimal(2281.42),
    amount: new Decimal(281.42),
    manufacturer: "BIG",
    remark: "",
  },
  {
    item_no: 8,
    name: "新倍比夹套",
    catalog_number: "NBC10-8",
    qty: 1,
    price: new Decimal(2281.42),
    amount: new Decimal(281.42),
    manufacturer: "BIG",
    remark: "",
  },
]
