export { basename } from "./regpath/basename"
export { extname } from "./regpath/extname"
export { isExclude, isExcludeFolders, isExcludeFiles } from "./regpath/isExclude"
export { isInclude } from "./regpath/isInclude"
export { isNotEndWith } from "./regpath/isNotEndWith"
export { isOnlyBetween } from "./regpath/isOnlyBetween"
export { toTitleCase, toCamelCase, toPascalCase, toKababCase, toSnakeCase } from "./regpath/toCase"
export { parentFolder, relativePaths, isRegRootFile, eraseDotSlash, parentPath, lastFolder } from "./regpath/toPath"
export { toObjectArray } from "./tools/toObjectArray"
