@url = https://api.openai.com/v1/chat/completions
### 
POST {{url}} HTTP/1.1
Content-Type: application/json 
Authorization: Bearer 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

{
  "model": "gpt-3.5-turbo",
  "messages": [{"role": "user", "content": "老师开讲座,讲了如何和青春期孩子相处,讲了一个给孩子留面子,充分信任, 写一篇感想, 300字以上"}],
  "temperature": 0.7
}